// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Si20k_Backend.Data;

#nullable disable

namespace Si20k_Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260331072847_SeedUsersVouchersCategories")]
    partial class SeedUsersVouchersCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Si20k_Backend.Model.Entities.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Si20k_Backend.Model.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ecd905d9-4030-4440-8a39-40f2257cf10a"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "shirts"
                        },
                        new
                        {
                            Id = new Guid("4660b1e2-d4c1-4162-9973-02ac762d1b55"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "pants"
                        },
                        new
                        {
                            Id = new Guid("bac4a38e-e093-42fd-8b26-054f41b3d1ee"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "jackets"
                        });
                });

            modelBuilder.Entity("Si20k_Backend.Model.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoldNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SellerId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000101"),
                            CategoryId = new Guid("ecd905d9-4030-4440-8a39-40f2257cf10a"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentPrice = 12000m,
                            Description = "100% cotton, relaxed fit",
                            ImageUrl = "https://images.unsplash.com/photo-1603252109303-2751441dd157?q=80&w=687",
                            Name = "White T-shirt with Red Stripes",
                            OriginalPrice = 20000m,
                            Quantity = 2,
                            SellerId = new Guid("00000000-0000-0000-0000-000000000002"),
                            SoldNumber = 156
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000102"),
                            CategoryId = new Guid("ecd905d9-4030-4440-8a39-40f2257cf10a"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentPrice = 15000m,
                            Description = "Cotton tee, breathable",
                            ImageUrl = "https://images.unsplash.com/photo-1603252109303-2751441dd157?q=80&w=687",
                            Name = "White Basic T-shirt",
                            OriginalPrice = 20000m,
                            Quantity = 10,
                            SellerId = new Guid("00000000-0000-0000-0000-000000000002"),
                            SoldNumber = 405
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000201"),
                            CategoryId = new Guid("4660b1e2-d4c1-4162-9973-02ac762d1b55"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentPrice = 14000m,
                            Description = "Stretch denim, Korean style",
                            ImageUrl = "https://images.unsplash.com/photo-1602293589930-45aad59ba3ab?q=80&w=687",
                            Name = "Blue Wide-Leg Jeans",
                            OriginalPrice = 20000m,
                            Quantity = 1,
                            SellerId = new Guid("00000000-0000-0000-0000-000000000002"),
                            SoldNumber = 143
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000202"),
                            CategoryId = new Guid("4660b1e2-d4c1-4162-9973-02ac762d1b55"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentPrice = 20000m,
                            Description = "Oversized trendy style",
                            ImageUrl = "https://images.unsplash.com/photo-1649566650740-cb0a625e1b40?q=80&w=687",
                            Name = "Baggy Jeans",
                            OriginalPrice = 20000m,
                            Quantity = 9,
                            SellerId = new Guid("00000000-0000-0000-0000-000000000002"),
                            SoldNumber = 312
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000301"),
                            CategoryId = new Guid("bac4a38e-e093-42fd-8b26-054f41b3d1ee"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentPrice = 15000m,
                            Description = "Lightweight, good sun protection",
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1673356301340-4522591be5f7?q=80&w=687",
                            Name = "Black Jacket",
                            OriginalPrice = 20000m,
                            Quantity = 2,
                            SellerId = new Guid("00000000-0000-0000-0000-000000000002"),
                            SoldNumber = 128
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000302"),
                            CategoryId = new Guid("bac4a38e-e093-42fd-8b26-054f41b3d1ee"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentPrice = 20000m,
                            Description = "Thick material, eye-catching color mix",
                            ImageUrl = "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?q=80&w=1072",
                            Name = "Red-Black Jacket with Hood",
                            OriginalPrice = 25000m,
                            Quantity = 5,
                            SellerId = new Guid("00000000-0000-0000-0000-000000000002"),
                            SoldNumber = 56
                        });
                });

            modelBuilder.Entity("Si20k_Backend.Model.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TokenCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@si20k.com",
                            FullName = "Root Admin",
                            PasswordHash = "$2a$11$ysmueFzp8i3JkEA/VC1OBuRuN6sD2IkqUeJ75Ji2m1oZqFhFK/nQ.",
                            PhoneNumber = "0123456789",
                            RefreshToken = "",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "seller@si20k.com",
                            FullName = "Demo Seller",
                            PasswordHash = "$2a$11$NcghptT3ej8INLT8rFIZWu22eBpa7hqcdLFlqaDxp6J47jxMymCsy",
                            PhoneNumber = "0987654321",
                            RefreshToken = "",
                            Role = "Seller",
                            Username = "Seller"
                        });
                });

            modelBuilder.Entity("Si20k_Backend.Model.Entities.Voucher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaxDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinOrder")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VoucherCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Vouchers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "10% off for first order",
                            DiscountAmount = 10m,
                            DiscountType = "Percent",
                            IsActive = true,
                            MinOrder = 100000m,
                            VoucherCode = "WELCOME10"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "50,000 VND off orders from 1,000,000 VND",
                            DiscountAmount = 50000m,
                            DiscountType = "Fixed",
                            IsActive = true,
                            MinOrder = 1000000m,
                            VoucherCode = "S50"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "20% off up to 500,000 VND",
                            DiscountAmount = 20m,
                            DiscountType = "Percent",
                            IsActive = true,
                            MaxDiscount = 500000m,
                            MinOrder = 500000m,
                            VoucherCode = "SALE20"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "15% off on summer collection",
                            DiscountAmount = 15m,
                            DiscountType = "Percent",
                            IsActive = true,
                            MinOrder = 300000m,
                            VoucherCode = "SUMMER15"
                        });
                });

            modelBuilder.Entity("Si20k_Backend.Model.Entities.CartItem", b =>
                {
                    b.HasOne("Si20k_Backend.Model.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Si20k_Backend.Model.Entities.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Si20k_Backend.Model.Entities.Product", b =>
                {
                    b.HasOne("Si20k_Backend.Model.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Si20k_Backend.Model.Entities.User", "Seller")
                        .WithMany("Products")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Si20k_Backend.Model.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Si20k_Backend.Model.Entities.User", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
